apiVersion: v1
kind: Service
metadata:
  name: blocky-dns-udp
  namespace: dns
  labels:
    app: blocky
spec:
  type: NodePort
  selector:
    app: blocky
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      nodePort: 30053
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: blocky-dns-tcp
  namespace: dns
  labels:
    app: blocky
spec:
  type: NodePort
  selector:
    app: blocky
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      nodePort: 30054
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: blocky-metrics
  namespace: dns
  labels:
    app: blocky
spec:
  type: NodePort
  selector:
    app: blocky
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 30055
      protocol: TCP
